name: fetch itch.io data

on:
  schedule:
    - cron: "0 00 * * 0"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  fetch-games:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: fetch my itch.io (all games)
        env:
          ITCH_API_KEY: ${{ secrets.ITCH_API_KEY }}
        run: |
          mkdir -p data
          mkdir -p .dump
          curl -H "Authorization: Bearer $ITCH_API_KEY" \
            "https://itch.io/api/1/key/my-games" \
            -o .dump/itch_games_all.json

          # status log
          echo "fetched from itch.io and saved to .dump/itch_games_all.json"

      - name: filter (published only) and prettify json output
        run: |
          jq '.games |= map(select(.published == true))' .dump/itch_games_all.json > data/itch_games.json

          jq --sort-keys '.' data/itch_games.json > data/itch_games_pretty.json
          mv data/itch_games_pretty.json data/itch_games.json

          # status log
          echo "filtered and prettified, saved to data/itch_games.json"

      - name: commit and push updated data
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add data/itch_games.json
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "auto update itch.io games data at $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
            git push
          fi